version: 2
updates:
  # React/TypeScript frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    assignees:
      - "alexcaulfield"

  # Flask backend
  - package-ecosystem: "pip"
    directory: "/flask-app"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    assignees:
      - "alexcaulfield"

  # Serverless deploy dependencies
  - package-ecosystem: "pip"
    directory: "/flask-app/.serverless"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    assignees:
      - "alexcaulfield"
